# Generated by Django 3.0.9 on 2022-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='initial_amount',
            new_name='initialamount',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='emailid',
            field=models.CharField(max_length=30),
        ),
    ]
